add docker support starter
netcode/quick-nodejs-starter pull request #2
Opened 2020-10-06 13:06 UTC by abdoutelb

2020-10-06 15:42 UTC, netcode requested changes

2020-10-06 15:42 UTC, netcode commented on Dockerfile
> +CMD ["npm","start"]
Can you please use yarn instead of npm ? Just to unify the tools used.

2020-10-06 15:43 UTC, netcode commented
@abdoutelb Thank you for your contribution, Can you make the change to use yarn in the docker file ?

2020-10-06 19:15 UTC, abdoutelb commented
> @abdoutelb Thank you for your contribution, Can you make the change to use yarn in the docker file ?

Sure Updated with readme instructions

2020-10-07 09:44 UTC, netcode approved these changes

2020-10-07 09:44 UTC, merged

2020-10-07 09:44 UTC, netcode commented
Merged. Thanks.